// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import robot.Robot;

/**
 *
 */
public class DriveArcTurnCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_leftPwr;
    private double m_rightPwr;
    private double m_dist;
    private double m_hdg;
    private int m_mode;
    private double m_TO;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    
    String line;

    Timer startTmr = new Timer();
    Timer stallTmr = new Timer();
    Timer stopTmr = new Timer();;
    int driveState, driveProfileFlag, stopFlag;
    double currPwr;
    double tgtYaw;
    double m_RemainTgtDist, m_RemainTgtYaw, currDist, currYaw, currSpeed;
    char m_Zone;
    int mTurnDir;
    boolean weHadMotionFlag;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveArcTurnCmd(double leftPwr, double rightPwr, double dist, double hdg, int mode, double TO) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_leftPwr = leftPwr;
        m_rightPwr = rightPwr;
        m_dist = dist;
        m_hdg = hdg;
        m_mode = mode;
        m_TO = TO;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	line = " ********** Starting DriveArcTurnCmd ***********";
    	line +=  " LeftPwr=" + m_leftPwr + " RtPwr=" + m_rightPwr;    	
    	line +=  " Dist=" + m_dist +  " Hdg=" + m_hdg +  " Mode=" + m_mode + " TO=" + m_TO;
    	Robot.drivetrain.setLoggingOn();
    	Robot.logger.appendLog(line);
    	System.out.println("DriveArcTurnCmd Init");
    	setTimeout(m_TO);

    	Robot.drivetrain.resetEncodersAndStats();
    	if (m_dist < 0) m_dist = m_dist * -1;			// Distance is positive speed can be neg. ??
    	weHadMotionFlag = false;						// false=NO motion yet, true=Motion has begun
    	stopFlag = 0;									// Clear stop flag to start
    	driveState = 0;								// We are just starting out will need to accel.
    	
    	startTmr.reset();
    	startTmr.start();    	

    	// Mode 0 = Go Distance
    	// Mode 1 = Go to heading
    	currYaw = Robot.drivetrain.getGyroYaw();    	
    	if (currYaw <= m_hdg) {
    		mTurnDir = +1;
    	} else {
    		mTurnDir = -1;
    	}
    	

    	//  		Yaw =  +-180degrees (+ turn right of straight) , ( -  turn left of straight)
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
      	// ---- Look up key data to start ----
    	currDist = Robot.drivetrain.getAverageDist();
    	currYaw = Robot.drivetrain.getGyroYaw();
    	currSpeed = Robot.drivetrain.getAverageSpeed();
    	m_RemainTgtDist = m_dist - currDist;
    	
    	m_RemainTgtYaw = m_hdg - currYaw;    	

    	// ----- State 0 (Initial Stop State) -----
    	if (driveState == 0){
    		// were are just starting, we need to move check timer for motion
    		if(startTmr.get() > 0.2) {
    			// we should be moving now
    			if (m_mode == 0) driveState = 1;
    			if (m_mode == 1) driveState = 2;	
    		}
    	}
    	
    	// ----- State 1 (Accel State) we are moving to a distance -----
    	if (driveState == 1){
    		// ----- Check Distance to see if we have are done) -----
    		if 	(m_RemainTgtDist <= 0){
        		// We have completed the requested distance so it's time to end
        		driveState = 3;    				
    		}
    	}
    	
    	if (driveState == 2){
    		// ----- Check Heading to see if we have are done) -----    		
    		if ((mTurnDir == 1) && (m_RemainTgtYaw <= 0)) {
				// We have completed the requested turn yaw so it's time to end
				driveState = 4;     				
    		}
    		if  ((mTurnDir == -1) && (m_RemainTgtYaw >= 0)) {
				// We have completed the requested turn yaw so it's time to end
				driveState = 5;    				
    		}
    	}
    		    		
    		// ----- Check to see if we have hit something -----    		
       		//if (Math.abs(Robot.drivetrain.getAverageSpeed()) <= 0.5){
    		//	// we have stopped moving we may have hit something so stop
    		//	driveState = 6;
    		//	//System.out.println("We have stopped");
    		//	//Robot.logger.appendLog("We were braking and have now stopped  (autoDriveFwdCmd) !");
    		//	return;
    		//}
    	
    	if (driveState < 3){
    		// we are not done so send pwr to drivetrain
        	Robot.drivetrain.tankDrive(m_leftPwr, m_rightPwr);
        	Robot.drivetrain.putZoneData( 7, m_dist, m_RemainTgtDist, tgtYaw, m_RemainTgtYaw );	// Log distance to tgt    	
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	if (isTimedOut()) return true;				// used in all modes

    	if ((driveState >= 3) && (driveState <= 5)) {
    		// Cmd has completed its distance
    		line = "DriveArcTurnCmd - Done - has reached its target !!";
    		Robot.logger.appendLog(line);
    		System.out.println(line) ;   		
    		return true;
    	}


    	if (driveState == 6) {
    		// We have stalled
    		line = "DriveArcTurnCmd - Has STOPPED (stalled) speed below 0.5 inches per sec. !!";
    		Robot.logger.appendLog(line);
    		System.out.println(line) ;
    		return true; 		// We have stopped so exit
    	}
    	
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
		line = "DriveFwd2Cmd has ended !!";
		Robot.logger.appendLog(line);
		System.out.println(line) ;
    	Robot.drivetrain.stopMtrs();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
